services:
  api:
    build:
      context: api/
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    env_file:
      - api/.env
    environment:
      POSTGRES_HOST: postgres

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    env_file:
      - api/.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d hop_query"]
      interval: 10s
      retries: 3
      timeout: 5s
      start_period: 5s
