include:
  - compose.api.yml
  - compose.db.yml

services:
  hop_query_ui:
    build:
      context: hop-query-ui/
    ports:
      - "8080:80"
    env_file:
      - hop-query-ui/.env
    depends_on:
      - hop_query_api
